export enum ORDER_STATUS {
  ORDER_PAID = "ORDER_PAID",
  ORDER_DELAY = "ORDER_DELAY",
  ORDER_RECEIVED = "ORDER_RECEIVED",
  ORDER_CANCELED = "ORDER_CANCELED",
}
export const QRSERVERURL = "http://localhost:5074/api/qr";
